In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1 )
print(arr1 * 2)

[1 2 3 4 5]
[ 2  4  6  8 10]


In [5]:
print(arr1 + 10)

[11 12 13 14 15]


In [ ]:
np_array = np.array([1, 2, 3]) # CREATING NUMPY ARRAY FROM LIST

print("Numpy_array:", np_array)
print("NumPy Array * 2:", np_array * 2)
print("NumPy Array + 10:", np_array + 10)
print("Dimensions of Numpy_array:", np_array.ndim)
print( np_array.shape)
print(np_array.size)
print(np_array.dtype)

Numpy_array: [1 2 3]
NumPy Array * 2: [2 4 6]
NumPy Array + 10: [11 12 13]
Dimensions of Numpy_array: 1
(3,)
3
int32


In [20]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2 * 2)
print(arr2 + 10)
print("Dimensions of arr2:", arr2.ndim)
print("Shape of arr2:", arr2.shape)
print("Size of arr2:", arr2.size)
print("Data type of arr2:", arr2.dtype)


[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[11 12 13]
 [14 15 16]]
Dimensions of arr2: 2
Shape of arr2: (2, 3)
Size of arr2: 6
Data type of arr2: int32


In [21]:
arr3 = np.array([[[1, 2, 3]], [[4, 5, 6]]])
print(arr3)
print(arr3 * 2)
print(arr3 + 10)
print("Dimensions of arr3:", arr3.ndim)
print("Shape of arr3:", arr3.shape)
print("Size of arr3:", arr3.size)
print("Data type of arr3:", arr3.dtype)

[[[1 2 3]]

 [[4 5 6]]]
[[[ 2  4  6]]

 [[ 8 10 12]]]
[[[11 12 13]]

 [[14 15 16]]]
Dimensions of arr3: 3
Shape of arr3: (2, 1, 3)
Size of arr3: 6
Data type of arr3: int32


In [30]:
#methods or built-in functions in numpy

#Creating an array of zeros
arr=np.zeros(5)
print(arr)
arr1=np.zeros((1,2))
print(arr1)
arr2=np.zeros((2,3))
print(arr2)



[0. 0. 0. 0. 0.]
[[0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
#Creating an array of ones
arr=np.ones(5)
print(arr)
arr1=np.ones((1,2))
print(arr1)
arr2=np.ones((2,3))
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [36]:
#Creating an array of evenly spaced values
arr = np.full((2, 3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [43]:
#randomly generated array
arr = np.random.random((2, 2))
print(arr)

[[0.82595963 0.71613584]
 [0.21281859 0.88285682]]


In [45]:
arr=np.eye(2)
print(arr)
arr1=np.eye(3)
print(arr1)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [65]:
arr=np.arange(1, 10, 2)
print(arr)

arr = np.random.randint(1, 100, 5)
print(arr)

arr=np.random.rand(5)
print(arr)

np.random.randint(1, 101, 5)



[1 3 5 7 9]
[33 96 50 59 60]
[0.68408644 0.25789616 0.31685952 0.82195581 0.85376419]


array([21, 97, 66, 55, 63])

In [69]:
marks = np.random.randint(1, 100,5)

print(marks)
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

[90 47 29 15 35]
Average: 43.2
Highest: 90
Lowest: 15


In [87]:
a1=np.array([1, 2, 3, 4, 5])
a2=np.array([6, 7, 8, 9, 10])
print("Addition:", a1 + a2)
print("Subtraction:", a1 - a2)
print("Multiplication:", a1 * a2)
print("Division:", a1 / a2)
print("Exponentiation:", a1 ** 2)
print("Square Root of a1:", np.sqrt(a1))
print("Square Root of a2:", np.sqrt(a2))
print("Maximum:", np.max(a1))
print("Minimum:", np.min(a1))
print("Average:", np.mean(a1))
print("Standard Deviation:", np.std(a1))
print("Variance:", np.var(a1))
print("length:", len(a1))
print("log:", np.log(a1))
print("Aabsolute:", np.abs(a1))
print("Sum:", np.sum(a1))
print("Sum:", np.sum(a2))
#Scalar Operations
print(a1 + 5)
print(a1 * 2)
print(a1 - 3)
print(a2 / 2)
print(a2 ** 2)
#comparison operator
print(a1 > 3)
print(a1[a1 > 3])
#concatenation
new = np.concatenate((a1, a2))
print("Concatenated Array:")
print(new)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Exponentiation: [ 1  4  9 16 25]
Square Root of a1: [1.         1.41421356 1.73205081 2.         2.23606798]
Square Root of a2: [2.44948974 2.64575131 2.82842712 3.         3.16227766]
Maximum: 5
Minimum: 1
Average: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
length: 5
log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Aabsolute: [1 2 3 4 5]
Sum: 15
Sum: 40
[ 6  7  8  9 10]
[ 2  4  6  8 10]
[-2 -1  0  1  2]
[3.  3.5 4.  4.5 5. ]
[ 36  49  64  81 100]
[False False False  True  True]
[4 5]
Concatenated Array:
[ 1  2  3  4  5  6  7  8  9 10]


In [89]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print("Array a:")
print(a)

b=np.arange(2,10)
print("Array b:")
print(b)
new_arr = b.reshape(4, 2)
print(new_arr)
print("Flatten_array:", a.flatten())
 #sorting
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
print("Original array:", arr)
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)


Array a:
[[1 2 3]
 [4 5 6]]
Array b:
[2 3 4 5 6 7 8 9]
[[2 3]
 [4 5]
 [6 7]
 [8 9]]
Flatten_array: [1 2 3 4 5 6]
Original array: [3 1 4 1 5 9 2 6 5 3 5]
Sorted array: [1 1 2 3 3 4 5 5 5 6 9]


In [90]:
a=np.array([1,2,3,4,5])
print("Last element:", a[-1])
print("First element:", a[0])
print("Element at index 2:", a[2])
print("Element at index 4:", a[4])



Last element: 5
First element: 1
Element at index 2: 3
Element at index 4: 5


In [91]:
import numpy as np
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]])
print("Row 1, Column 2:", matrix[0, 1])
print("Second row:", matrix[1])

Row 1, Column 2: 20
Second row: [40 50 60]


In [96]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::-1])
print(arr[::2])

[20 30 40]
[10 20 30]
[30 40 50]
[50 40 30 20 10]
[10 30 50]


In [97]:
import numpy as np
arr = np.arange(1, 13)
matrix = arr.reshape(3, 4)
cube = arr.reshape(2, 2, 3)
print("Original:", arr)
print("\n3 x 4:")
print(matrix)
print("\n3D shape:", cube.shape)
print(cube)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

3 x 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

3D shape: (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print("Original:")
print(matrix)
print("\nTranspose:")
print(matrix.T)
print("Transpose shape:")
print(matrix.T.shape)

Original:
[[1 2 3]
 [4 5 6]]

Transpose:
[[1 4]
 [2 5]
 [3 6]]
Transpose shape:
(3, 2)


In [99]:
import numpy as np
arr = np.array([1, 4, 9, 16])
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(np.array([0, 1, 2])))
print("Log:", np.log(np.array([1, np.e, np.e**2])))
print("Absolute value:", np.abs(np.array([-5, -2, 3])))

Square root: [1. 2. 3. 4.]
Exponential: [1.         2.71828183 7.3890561 ]
Log: [0. 1. 2.]
Absolute value: [5 2 3]
